variable "env" {}
variable "vpc_cidr_block" {}
variable "frontend_subnet" {}
variable "backend_subnet" {}
variable "db_subnet" {}
variable "availability_zones" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_route_table_id" {}
