variable "env" {}
variable "instance_type" {}
variable "zone_id" {}
variable "vault_token" {}
variable "vpc_cidr_block" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_route_table_id" {}
variable "frontend_subnet" {}
variable "backend_subnet" {}
variable "db_subnet" {}
variable "availability_zones" {}
variable "public_subnet" {}
variable "bastion_nodes" {}
variable "prometheus_nodes" {}
variable "server_app_port_sg_cidr" {}