format_version: 10
pipelines:
  expense-tf-destroy:
    group: Terraform
    materials:
      git-4f9022f:
        git: https://github.com/anand-320/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:rsFNC5K8WN5aliy5fraRpQ==:NEaOhSKi7Ks9CW+vP19ih3f8aIcEKDzAn48vnkBQsvk=
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-destroy:
              tasks:
              - exec: {command: terraform, arguments: [ "init", "-backend-config=env-dev/state.tfvars" ], run_if: passed}
              - exec: {command: terraform, arguments: [ "destroy", "-var-file=env-dev/main.tfvars", "-auto-approve" ], run_if: passed}
      - prod:
          fetch_materials: true
          environment_variables:
          approval:
            type: success
          jobs:
            terraform-apply:
              tasks:
                - exec: { command: terraform, arguments: [ "init", "-backend-config=env-prod/state.tfvars" ], run_if: passed }
                - exec: { command: terraform, arguments: [ "destroy", "-var-file=env-prod/main.tfvars", "-auto-approve" ], run_if: passed }


